### PR TITLE
Add a component diagram to the documentation

### PR DESCRIPTION
**Pull request by pauldoomgov**
Preview in https://github.com/GSA-TTS/gitlab-runner-cloudgov/blob/95a2ee516073dd914b15f46a11e484ddf017196c/README.md

Addresses https://github.com/GSA-TTS/devtools-program/issues/83

### CODE REVIEW

**Review by rahearn — APPROVED** [review]
nice!

**Review by zjrgov — APPROVED** [review]
Yay for terminology consistentizing!

But how do we pronounce `GLR[M/W/S]`?

**Comment by rahearn** [comment]
> But how do we pronounce `GLR[M/W/S]`?

GLRM - glorm
GLRW - glower
GLRS - glares

**Comment by pauldoomgov** [comment]
> > But how do we pronounce `GLR[M/W/S]`?
> 
> GLRM - glorm GLRW - glower GLRS - glares

"The glorm instantiated a Redis glares, then ran the test suite in the glower."

Trivially understandable to even the most casual of observers.

**Pull request merged**
